sonar.projectKey=inventory-qas
sonar.projectName=Inventory QAS
sonar.projectVersion=0.6.0-SNAPSHOT

sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main/java,frontend/app,frontend/components,frontend/lib
sonar.tests=backend/src/test/java,tests

sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/.next/**,**/node_modules/**,**/*.json,**/realm-export.json
sonar.test.exclusions=**/test/**
